// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZNxjfKpEQESaaUrSzdcXDkU8yVJJ92bk',
    appId: '1:518386985010:web:7d063c911feabf3dacb42b',
    messagingSenderId: '518386985010',
    projectId: 'sss-store-1365e',
    authDomain: 'sss-store-1365e.firebaseapp.com',
    storageBucket: 'sss-store-1365e.firebasestorage.app',
    measurementId: 'G-CXPPNG1Q72',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN-lVeZbsOth6g1Net2lbadiwN2swATEM',
    appId: '1:518386985010:android:5aec3e85b1dd6d90acb42b',
    messagingSenderId: '518386985010',
    projectId: 'sss-store-1365e',
    storageBucket: 'sss-store-1365e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiGjdyj7REgS232mg9DeNtqdSSx2fdzpU',
    appId: '1:518386985010:ios:9924c409769073a3acb42b',
    messagingSenderId: '518386985010',
    projectId: 'sss-store-1365e',
    storageBucket: 'sss-store-1365e.firebasestorage.app',
    iosBundleId: 'com.example.sssStarsFlutterAssessment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiGjdyj7REgS232mg9DeNtqdSSx2fdzpU',
    appId: '1:518386985010:ios:9924c409769073a3acb42b',
    messagingSenderId: '518386985010',
    projectId: 'sss-store-1365e',
    storageBucket: 'sss-store-1365e.firebasestorage.app',
    iosBundleId: 'com.example.sssStarsFlutterAssessment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZNxjfKpEQESaaUrSzdcXDkU8yVJJ92bk',
    appId: '1:518386985010:web:4d3959f0b7666804acb42b',
    messagingSenderId: '518386985010',
    projectId: 'sss-store-1365e',
    authDomain: 'sss-store-1365e.firebaseapp.com',
    storageBucket: 'sss-store-1365e.firebasestorage.app',
    measurementId: 'G-7SXVCE0DML',
  );
}
